tagFormat: v${version}
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/git"
  - - "@semantic-release/github"
    - draftRelease: true

branches:
  - name: 'main'




