# Common workflow template (common.yml)
name: Common Workflow

on:
  workflow_call:

jobs:
  common-job:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "This is a common step."
      - name: Check out Repository
        uses: actions/checkout@v3




