# This workflow builds, tests, and releases the modules.
name: Publish Release to Github Packages
on:
  release:
    types: [published, released]

env:
  SEMANTIC_VERSION: ${{ github.event.release.tag_name }}
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  # build
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'maven'
      - name: Debug output
        run: |
          echo "Semantic Version: ${IMAGE_NAME}:${SEMANTIC_VERSION}"
      - name: Maven build
        run: mvn install
      - name: Build and push Docker image
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          push: true
          tags: rodgerr/${IMAGE_NAME}:${SEMANTIC_VERSION}