name: Semantic Release

on:
  workflow_dispatch

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Semantic release
        run: |
          sudo npm install -g \
            semantic-release@20.1.0 \
            @semantic-release/git@10.0.1 \
            @semantic-release/release-notes-generator@10.0.3 \
            @semantic-release/github@8.0.7
      - name: Release and Publish
        run: semantic-release